# Generated by Django 5.2.6 on 2025-10-23 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearguide', '0002_initial'),
        ('sportlibrary', '0003_merge_0002_alter_sport_id_0002_remove_sport_gears'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='gears',
            field=models.ManyToManyField(related_name='gear_relations', to='gearguide.gear'),
        ),
    ]
