# Generated by Django 5.2.7 on 2025-10-23 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0001_initial'),
        ('videos', '0002_remove_sport_slug_remove_video_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sportlibrary.sport'),
        ),
        migrations.DeleteModel(
            name='Sport',
        ),
    ]
