# Generated by Django 5.2.7 on 2025-12-09 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_add_missing_fields'),
        ('videos', '0003_video_total_likes_alter_video_description_and_more'),
    ]

    operations = [
    ]
