# Generated by Django 5.2.5 on 2025-10-24 13:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(db_index=True, max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('hits', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_hit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-hits', '-last_hit'], name='landingpage_hits_a384f9_idx')],
                'unique_together': {('view_name', 'path')},
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('category', models.CharField(choices=[('library', 'Sports Library'), ('community', 'Community'), ('gearguide', 'Gear Guide'), ('video', 'Video')], default='library', max_length=20)),
                ('image_url', models.URLField(blank=True, default='')),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WhatsHot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, help_text="Label kecil seperti 'Trending • Library'", max_length=80)),
                ('priority', models.IntegerField(default=0, help_text='Semakin besar, semakin di atas')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whats_hot_items', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': "What's Hot",
                'verbose_name_plural': "What's Hot",
                'ordering': ('-priority', '-created_at'),
            },
        ),
    ]
