# Generated by Django 5.2.7 on 2025-10-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageHit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(db_index=True, max_length=100)),
                ('path', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('hits', models.PositiveIntegerField(db_index=True, default=0)),
                ('last_hit', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-hits', '-last_hit'], name='landingpage_pa_hits_de2eb5_idx')],
                'unique_together': {('view_name', 'path')},
            },
        ),
    ]
