# Generated by Django 5.2.6 on 2025-10-23 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_alter_testimonial_options_alter_testimonial_category_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pagehit',
            new_name='landingpage_hits_a384f9_idx',
            old_name='landingpage_pa_hits_de2eb5_idx',
        ),
    ]
