# Generated by Django 5.2.7 on 2025-10-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0005_rename_landingpage_pa_hits_de2eb5_idx_landingpage_hits_a384f9_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
