# Generated by Django 5.2.7 on 2025-10-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_remove_testimonial_rating_alter_testimonial_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='category',
            field=models.CharField(choices=[('library', 'Sports Library'), ('community', 'Community'), ('gearguide', 'Gear Guide'), ('video', 'Video')], default='library', max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
