# Generated by Django 5.2.7 on 2025-10-21 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sportlibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=50, null=True)),
                ('ecommerce_link', models.URLField(blank=True, null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Pemula'), ('intermediate', 'Menengah'), ('advanced', 'Lanjutan')], default='beginner', max_length=50)),
                ('tips', models.TextField(blank=True, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gears', to='sportlibrary.sport')),
            ],
        ),
    ]
