# Generated by Django 5.2.7 on 2025-10-23 13:32
# Generated by Django 5.2.7 on 2025-10-23 07:32

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('function', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=50, null=True)),
                ('ecommerce_link', models.URLField(blank=True, null=True)),
                ('level', models.CharField(choices=[('beginner', 'Pemula'), ('intermediate', 'Menengah'), ('advanced', 'Lanjutan')], default='beginner', max_length=50)),
                ('recommended_brands', models.JSONField(blank=True, default=list, null=True)),
                ('materials', models.JSONField(blank=True, default=list, null=True)),
                ('care_tips', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
            ],
            options={
                'verbose_name': 'Gear',
                'verbose_name_plural': 'Gears',
                'ordering': ['name'],
            },
        ),
    ]
