# Generated by Django 5.2.7 on 2025-12-08 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gearguide', '0001_initial'),
        ('sportlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_items', to='sportlibrary.sport'),
        ),
    ]
