# Generated by Django 5.2.7 on 2025-10-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearguide', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gear',
            old_name='tips',
            new_name='care_tips',
        ),
        migrations.AddField(
            model_name='gear',
            name='function',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gear',
            name='materials',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gear',
            name='recommended_brands',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gear',
            name='tags',
            field=models.TextField(blank=True, null=True),
        ),
    ]
