# Generated by Django 5.2.7 on 2025-10-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearguide', '0002_rename_tips_gear_care_tips_gear_function_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'ordering': ['name'], 'verbose_name': 'Gear', 'verbose_name_plural': 'Gears'},
        ),
        migrations.RenameField(
            model_name='gear',
            old_name='difficulty_level',
            new_name='level',
        ),
        migrations.AlterField(
            model_name='gear',
            name='materials',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='recommended_brands',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
