# Generated by Django 5.2.7 on 2025-10-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearguide', '0002_rename_tips_gear_care_tips_gear_function_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gear',
            options={'ordering': ['name'], 'verbose_name': 'Gear', 'verbose_name_plural': 'Gears'},
        ),
        migrations.RemoveField(
            model_name='gear',
            name='difficulty_level',
        ),
        migrations.AddField(
            model_name='gear',
            name='level',
            field=models.CharField(choices=[('beginner', 'Pemula'), ('intermediate', 'Menengah'), ('advanced', 'Lanjutan')], default='beginner', max_length=50),
        ),
        migrations.AlterField(
            model_name='gear',
            name='materials',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='recommended_brands',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
