# Generated by Django 5.2.7 on 2025-10-22 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearguide', '0003_alter_gear_options_remove_gear_difficulty_level_and_more'),
        ('sportlibrary', '0002_alter_sport_options_sport_benefits_sport_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_items', to='sportlibrary.sport'),
        ),
    ]
