# Generated by Django 5.2.5 on 2025-10-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=50)),
                ('image', models.CharField(blank=True, max_length=500, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['-views'], name='metrics_vie_views_f67d83_idx'), models.Index(fields=['category', '-views'], name='metrics_vie_categor_8e0a78_idx')],
            },
        ),
    ]
