# Generated by Django 5.2.7 on 2025-10-21 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olahraga_favorit', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True, null=True)),
                ('foto_profil', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('video_ditonton', models.IntegerField(default=0)),
                ('artikel_dibaca', models.IntegerField(default=0)),
                ('panduan_selesai', models.IntegerField(default=0)),
                ('badge', models.CharField(blank=True, max_length=100, null=True)),
                ('terakhir_aktif', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
