# Generated by Django 5.2.7 on 2025-10-21 18:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='preferensi',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='artikel_dibaca',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='panduan_selesai',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='terakhir_aktif',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='video_ditonton',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='olahraga_favorit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ProgressTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('olahraga_dipelajari', models.CharField(max_length=100)),
                ('video_ditonton', models.CharField(blank=True, max_length=200, null=True)),
                ('artikel_dibaca', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]