# Generated by Django 5.2.7 on 2025-10-22 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_activitylog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progresstracker',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='ProgressTracker',
        ),
    ]
