# Generated by Django 5.2.5 on 2025-10-23 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0005_userprofile_achievements_userprofile_articles_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='achievements',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='articles_read',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='badges',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tanggal_gabung',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='videos_watched',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='foto_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
