# Generated by Django 5.2.5 on 2025-10-23 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0007_sportprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('MODULE_ACCESS', 'Accessed Module'), ('VIDEO_VIEW', 'Viewed Video'), ('FORUM_POST', 'Posted in Forum'), ('TESTIMONIAL_SUBMIT', 'Submitted Testimonial'), ('ADMIN_CREATE', 'Admin: Created Item'), ('ADMIN_UPDATE', 'Admin: Updated Item'), ('ADMIN_DELETE', 'Admin: Deleted Item')], max_length=20)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
