# Generated by Django 5.2.5 on 2025-10-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0008_activitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportprogress',
            options={'ordering': ['-last_accessed']},
        ),
        migrations.AlterField(
            model_name='sportprogress',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sportprogress',
            name='time_spent',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
