# Generated by Django 5.2.5 on 2025-10-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0010_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='foto_profil',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
