# Generated by Django 5.2.7 on 2025-12-08 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gearguide', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='sports/')),
                ('category', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('rules', models.JSONField(default=list)),
                ('techniques', models.JSONField(default=list)),
                ('benefits', models.JSONField(default=list)),
                ('popular_countries', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('gears', models.ManyToManyField(related_name='gear_relations', to='gearguide.gear')),
            ],
        ),
        migrations.CreateModel(
            name='SavedSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_sports', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='sportlibrary.sport')),
            ],
            options={
                'unique_together': {('user', 'sport')},
            },
        ),
    ]
