# Generated by Django 5.2.7 on 2025-10-23 07:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gearguide', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('rules', models.JSONField(default=list)),
                ('techniques', models.JSONField(default=list)),
                ('benefits', models.JSONField(default=list)),
                ('popular_countries', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('gears', models.ManyToManyField(related_name='gear_relations', to='gearguide.gear')),
            ],
        ),
    ]
