# Generated by Django 5.2.7 on 2025-10-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('difficulty', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('history', models.TextField()),
                ('rules', models.JSONField(default=list)),
                ('techniques', models.JSONField(default=list)),
                ('benefits', models.JSONField(default=list)),
                ('popular_countries', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
            ],
        ),
    ]
