# Generated by Django 5.2.7 on 2025-10-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sports/'),
        ),
    ]
