# Generated by Django 5.2.7 on 2025-10-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
