# Generated by Django 4.2.23 on 2025-12-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearguide', '0002_initial'),
        ('sportlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'Sport', 'verbose_name_plural': 'Sports'},
        ),
        migrations.AlterField(
            model_name='sport',
            name='gears',
            field=models.ManyToManyField(blank=True, related_name='gear_relations', to='gearguide.gear'),
        ),
        migrations.AlterModelTable(
            name='savedsport',
            table='sportlibrary_savedsport',
        ),
        migrations.AlterModelTable(
            name='sport',
            table='sportlibrary_sport',
        ),
    ]
