# Generated by Django 4.2.23 on 2025-10-22 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sportlibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={'ordering': ['name'], 'verbose_name': 'Sport', 'verbose_name_plural': 'Sports'},
        ),
        migrations.AddField(
            model_name='sport',
            name='benefits',
            field=models.JSONField(default=list, help_text='List of benefits'),
        ),
        migrations.AddField(
            model_name='sport',
            name='category',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('water', 'Water'), ('extreme', 'Extreme'), ('team', 'Team'), ('individual', 'Individual')], default='belum di set', max_length=50),
        ),
        migrations.AddField(
            model_name='sport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='description',
            field=models.TextField(default='no description yet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='difficulty',
            field=models.CharField(choices=[('pemula', 'Pemula'), ('menengah', 'Menengah'), ('lanjutan', 'Lanjutan')], default='easy', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='history',
            field=models.TextField(default='no history'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='name',
            field=models.CharField(default='no name', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sport',
            name='popular_countries',
            field=models.JSONField(default=list, help_text='List of countries where sport is popular'),
        ),
        migrations.AddField(
            model_name='sport',
            name='tags',
            field=models.JSONField(default=list, help_text='List of tags for searching'),
        ),
        migrations.AddField(
            model_name='sport',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='sports/thumbnails/'),
        ),
        migrations.AddField(
            model_name='sport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField(help_text='YouTube or other video platform URL')),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='sportlibrary.sport')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('technique_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order of display')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='techniques', to='sportlibrary.sport')),
            ],
            options={
                'verbose_name': 'Technique',
                'verbose_name_plural': 'Techniques',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_text', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order of display')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='sportlibrary.sport')),
            ],
            options={
                'verbose_name': 'Rule',
                'verbose_name_plural': 'Rules',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('function', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('required', models.BooleanField(default=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('price_range', models.CharField(blank=True, max_length=50, null=True)),
                ('ecommerce_link', models.URLField(blank=True, null=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Pemula'), ('intermediate', 'Menengah'), ('advanced', 'Lanjutan')], default='beginner', max_length=50)),
                ('recommended_brands', models.TextField(blank=True, null=True)),
                ('materials', models.TextField(blank=True, null=True)),
                ('care_tips', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_gears', to='sportlibrary.sport')),
            ],
            options={
                'verbose_name': 'Gear',
                'verbose_name_plural': 'Gears',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SportProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_videos', models.ManyToManyField(blank=True, related_name='completed_by', to='sportlibrary.video')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='sportlibrary.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sport Progress',
                'verbose_name_plural': 'Sport Progress',
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'sport')},
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, help_text='Personal notes about this sport')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='sportlibrary.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'sport')},
            },
        ),
    ]
