# Generated by Django 5.2.7 on 2025-10-23 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='gears',
        ),
    ]
