# Generated by Django 5.2.7 on 2025-10-26 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0002_add_image_field'),
    ]

    operations = [
    ]
