# Generated by Django 5.2.6 on 2025-10-23 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0002_alter_sport_id'),
        ('sportlibrary', '0002_remove_sport_gears'),
    ]

    operations = [
    ]
