# Generated by Django 5.2.7 on 2025-10-22 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearguide', '0004_alter_gear_sport'),
        ('sportlibrary', '0002_alter_sport_options_sport_benefits_sport_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='sport',
        ),
        migrations.AlterUniqueTogether(
            name='sportprogress',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='sportprogress',
            name='completed_videos',
        ),
        migrations.RemoveField(
            model_name='sportprogress',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='sportprogress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='sport',
        ),
        migrations.RemoveField(
            model_name='video',
            name='sport',
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={},
        ),
        migrations.RemoveField(
            model_name='sport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='sport',
            name='gears',
            field=models.ManyToManyField(related_name='gear_relations', to='gearguide.gear'),
        ),
        migrations.AddField(
            model_name='sport',
            name='rules',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sport',
            name='techniques',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sport',
            name='benefits',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sport',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sport',
            name='difficulty',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='sport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sport',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sport',
            name='popular_countries',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='sport',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
        migrations.DeleteModel(
            name='Gear',
        ),
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.DeleteModel(
            name='SportProgress',
        ),
        migrations.DeleteModel(
            name='Technique',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
