# Generated by Django 4.2.23 on 2025-12-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearguide', '0002_initial'),
        ('sportlibrary', '0002_alter_sport_options_alter_sport_gears_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sport',
            options={},
        ),
        migrations.RemoveField(
            model_name='sport',
            name='image',
        ),
        migrations.AlterField(
            model_name='sport',
            name='gears',
            field=models.ManyToManyField(related_name='gear_relations', to='gearguide.gear'),
        ),
        migrations.AlterModelTable(
            name='savedsport',
            table=None,
        ),
        migrations.AlterModelTable(
            name='sport',
            table=None,
        ),
    ]
