# Generated by Django 5.2.5 on 2025-10-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gearguide', '0001_initial'),
        ('sportlibrary', '0002_alter_sport_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='gears',
            field=models.ManyToManyField(related_name='gear_relations', to='gearguide.gear'),
        ),
    ]
