# Generated by Django 4.2.23 on 2025-12-10 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0003_alter_sport_options_remove_sport_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sports/'),
        ),
    ]
