# Generated by Django 4.2.23 on 2025-10-22 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0003_broken_backup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
