# Generated by Django 4.2.23 on 2025-12-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0003_add_image_field'),
        ('sportlibrary', '0004_sport_image'),
    ]

    operations = [
    ]
