# Generated by Django 5.2.5 on 2025-10-23 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0004_savedsport'),
        ('sportlibrary', '0004_sport_gears'),
    ]

    operations = [
    ]
