# Generated by Django 5.2.6 on 2025-10-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0004_sport_gears'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sports/'),
        ),
    ]
