# Generated by Django 5.2.5 on 2025-10-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sportlibrary', '0005_merge_0004_savedsport_0004_sport_gears'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SavedSport',
        ),
    ]
