# Generated by Django 5.2.6 on 2025-10-22 18:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('mainPage', '0003_alter_testimonial_options_alter_testimonial_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='category',
            field=models.CharField(choices=[('library', 'Sports Library'), ('community', 'Community'), ('gearguide', 'Gear Guide'), ('video', 'Video')], db_index=True, default='library', max_length=20),
        ),
        migrations.CreateModel(
            name='WhatsHot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('label', models.CharField(blank=True, help_text="Label kecil seperti 'Trending • Library'", max_length=80)),
                ('priority', models.IntegerField(default=0, help_text='Semakin besar, semakin di atas')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whats_hot_items', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': "What's Hot",
                'verbose_name_plural': "What's Hot",
                'ordering': ('-priority', '-created_at'),
            },
        ),
    ]
