# Generated by Django 5.2.5 on 2025-10-24 16:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sport', models.CharField(choices=[('bulu-tangkis', 'Bulu Tangkis'), ('yoga', 'Yoga'), ('tenis', 'Tenis'), ('renang', 'Renang'), ('panahan', 'Panahan'), ('lari', 'Lari'), ('basket', 'Basket'), ('futsal', 'Futsal'), ('bersepeda', 'Bersepeda'), ('tenis-meja', 'Tenis Meja'), ('voli', 'Voli'), ('panjat-tebing', 'Panjat Tebing'), ('muay-thai', 'Muay Thai'), ('golf', 'Golf'), ('selancar', 'Selancar'), ('pencak-silat', 'Pencak Silat'), ('baseball', 'Baseball'), ('skateboard', 'Skateboard'), ('calisthenics', 'Calisthenics'), ('wall-climbing', 'Wall Climbing')], max_length=50)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='forum_posts', to='sportforum.tag')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='sportforum.forumpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
