# Generated by Django 5.2.7 on 2025-10-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportforum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumpost',
            name='sport',
            field=models.CharField(choices=[('bulu-tangkis', 'Bulu Tangkis'), ('yoga', 'Yoga'), ('tenis', 'Tenis'), ('renang', 'Renang'), ('panahan', 'Panahan'), ('lari', 'Lari'), ('basket', 'Basket'), ('futsal', 'Futsal'), ('bersepeda', 'Bersepeda'), ('tenis-meja', 'Tenis Meja'), ('voli', 'Voli'), ('panjat-tebing', 'Panjat Tebing'), ('muay-thai', 'Muay Thai'), ('golf', 'Golf'), ('selancar', 'Selancar'), ('pencak-silat', 'Pencak Silat'), ('baseball', 'Baseball'), ('skateboard', 'Skateboard'), ('calisthenics', 'Calisthenics'), ('wall-climbing', 'Wall Climbing')], max_length=50),
        ),
        migrations.DeleteModel(
            name='SportCategory',
        ),
    ]
